### ISSUE TITLE
Genric button

### ISSUE THREAD

**Issue by AndreiCherniaev** [alkysamara/SpaceGradientAltiumLibraries#14]
Genric button не очень-то generic... 

Для сравнения первая попавшаяся [кнопка ](https://datasheet.lcsc.com/lcsc/2108131730_Korean-Hroparts-Elec-K2-1839SP-C4SW-02_C164133.pdf ) требует ширину 11 мм, а не 7.6мм.  [Эта ](https://www.chipdip.ru/product/kls7-ts6604-4.3-180-b-it-1102s)кнопка тоже плохо ложится.

Предлагаю скорректировать футпринт.

![изображение](https://user-images.githubusercontent.com/27889022/163900185-e1070cef-fad0-4621-b516-2e1a6461842f.png)

**Comment by AndreiCherniaev** [comment]
[BTNs.zip](https://github.com/alkysamara/SpaceGradientAltiumLibraries/files/8508985/BTNs.zip)

**Comment by alkysamara** [comment]
А если открыть 3д то сразу будет понятно почему. Название давно поменял, оно действительно могло вводить в заблуждение. Это допотопный футпринт года эдак 13го. Коммент, чтобы закрыть issue
