### ISSUE TITLE
Начало координат на 1м пине или по центру?

### ISSUE THREAD

**Issue by AndreiCherniaev** [alkysamara/SpaceGradientAltiumLibraries#6]
Как правильно? Начало координат на 1м пине или по центру?
Предлагаю решить и записать в readme.
![1pin](https://user-images.githubusercontent.com/27889022/141535110-d1d685ca-e914-4f07-aea3-0110809f58c9.png)

**Comment by AndreiCherniaev** [comment]
Ещё пример (тут ещё и название требует корректировки)
![butt1](https://user-images.githubusercontent.com/27889022/141644053-4be64cb1-7ba1-4699-a51a-9cfe2d618eb1.png)

**Comment by AndreiCherniaev** [comment]
@AnatolyRx что думаете?

**Comment by alkysamara** [comment]
По хорошему - в центре. Но не у всех компонентов его легко найти. Так что по обстоятельствам. Желательно только у однотипных компонентов (аля те же SO-8, SO-8M, SO-8N и т.д.) были одинаковые для взаимозаменяемости.
Массового фикса не будет, а то полетят все текущие проекты. Предлагаю просто при добавлении новых ставить на центр. При сложности его определения - на 1 пин.
