### ISSUE TITLE
HiZ выводы резистора

### ISSUE THREAD

**Issue by AndreiCherniaev** [alkysamara/SpaceGradientAltiumLibraries#8]
Почему у резистора выбран тип HiZ а не Passive?
![HiZ](https://user-images.githubusercontent.com/27889022/141679201-e7383da6-b3c7-47c6-b153-a45e317854c9.png)

**Comment by alkysamara** [comment]
Это фича для хоть какой-то автоматизации процесса проверки схемы. Не нужно - используйте Resistor_passive
